feat: Creating an example of an email summary
llamaapi/llama-api-docs pull request #15
Opened 2024-01-16 14:58 UTC by TiagoVictor

2024-01-16 16:29 UTC, TeodoroRaulino commented on essentials/function.mdx
> +  "model": "codellama-7b-instruct",
Why are you using two different models?

2024-01-16 16:30 UTC, TeodoroRaulino approved these changes

2024-01-16 16:36 UTC, TeodoroRaulino commented on essentials/function.mdx
> +### Example 4: `get_email_resume`
@fuchsfelipel , what do you think of the idea of ​​function calling having just one example that is already very complete and adding the other examples to a page that only contains examples ? So each example can be better detailed on this examples page

2024-01-16 16:38 UTC, TeodoroRaulino commented on essentials/function.mdx
> +### Example 4: `get_email_resume`
Could be on another task

2024-01-16 17:07 UTC, TiagoVictor commented on essentials/function.mdx
> +  "model": "codellama-7b-instruct",
Corrected to use only one model

2024-01-19 12:02 UTC, fuchsfelipel requested changes

2024-01-19 12:02 UTC, fuchsfelipel commented on essentials/function.mdx
> +### Example 4: `get_email_resume`
I agree! In fact, for this specific example, I'd move it to a page called `Tutorial` and give a step-by-step explanation

2024-01-19 12:02 UTC, fuchsfelipel commented on essentials/function.mdx
> +
When you move this to the `Tutorial` page, give an explanation of how it works:

Eg. On the code below, what actually happens is:
1. We send the request to the LLM
2. The LLM sees your emails using IMAP
3. ....

2024-01-19 12:02 UTC, fuchsfelipel commented on essentials/function.mdx
> +    {"role": "user", "content": "Make a resume from my last e-mail, login: tiagovictordeoliveira@gmail.com and password: nnmy fvbx sucz gxdu"},
This is a big security problem.... your email and password are now public to the world! I imagine you already expired your password... but change your email so you don't get too much SPAM messages

2024-01-19 12:02 UTC, fuchsfelipel commented on essentials/function.mdx
> +    {"role": "user", "content": "Make a resume from my last e-mail, login: tiagovictordeoliveira@gmail.com and password: nnmy fvbx sucz gxdu"},
```suggestion
    {"role": "user", "content": "Make a summary of my last e-mail, login: tiagovictordeoliveira@gmail.com and password: nnmy fvbx sucz gxdu"},
```

2024-01-19 12:02 UTC, fuchsfelipel commented on essentials/function.mdx
> +        "name": "get_email_resume",
Rename to `get_email_summary`

In english:
`resume` quer dizer `continuar``
`summary` quer dizer `resumo`

2024-01-19 12:04 UTC, fuchsfelipel commented on essentials/function.mdx
> +    {"role": "user", "content": "Make a resume from my last e-mail, login: tiagovictordeoliveira@gmail.com and password: nnmy fvbx sucz gxdu"},
https://stackoverflow.com/questions/2110595/redaction-in-git

2024-01-19 19:31 UTC, closed without merging